/*
const Define = {
	SHOW: 'show',
	HIDE: 'hide',
	ACTION: 'action',
	ON_CLICK: 'onclick',
	DISABLED: 'disabled',
	SRC: 'src',
	DISPLAY: 'display',
	NONE: 'none',
	KEYUP: 'keyup',
	BLOCK: 'block',
	CLICK: 'click',
	SPAN: 'span',
	SEP: ',',
	SPACE: ' ',
	COUNT_0: 0,
	COUNT_1: 1,
	COUNT_2: 2,
	COUNT_3: 3,
	COUNT_4: 4,
	COUNT_5: 5,
	COUNT_6: 6,
	COUNT_7: 7,
	COUNT_8: 8,
	COUNT_9: 9,
	COUNT_10: 10,
	COUNT_15: 15,	
	QUESTION: '?',
	VISIBILITY: 'visibility',
	HIDDEN: 'hidden',
	SEC_MILI_1000: 1000,
	INDEX_0: 0,
	INDEX_1: 1,
	INDEX_2: 2,
	INDEX_3: 3,
	INDEX_4: 4,	
	SIGNUP_SUCCESS: '회원 가입이 성공하였습니다.',
	STR_BLANK: '',
	INPUT: 'input',
	LABEL: 'label',
	YYYY_MM_DD: 'yyyy-mm-dd',
	SELECTED: 'selected',
	CHECKED: 'checked',
	COLON_CHECKED: ':checked',
	PAGE_0: 0,
	CLASS: 'class',
	ID: 'id',
	ASC: 'asc',
	DESC: 'desc',
//	CHECKED:':checked',
	DATA_SEQ: 'data-seq',
	DATA_ROAD:'data-road',
	DATA_DONG:'data-dong',
	DATA_REG_DTIME:'data-reg-dtime',
	DATA_DSR_SEQ:'data-dsr-seq',
	YES: 'yes',
	INSERT:'insert',
	EDIT:'edit',
	DELETE:'delete',
	UPDATE:'update',
	HOUR:'시',
	MONTH_1:1,
	DATA_LAT:'data-lat',
	DATA_LOG:'data-log',
	WIDTH:'width',
	HEIGHT:'height',
	STYLE:'style',
	START:'start',
	STOP:'stop',
	DATA_MODE:'data-mode',
	DATA_MODE_CAMERA:'data-mode-camera',
	CHATTING:'chatting',
	CMD:'cmd',
	NOT_CHATTING:'not-chatting',
	MENU:'menu',
	TEXT:'text',
	SEL:'sel',
	ENTER:'\n',
	SEC_MILI_300:300,
	SEC_MILI_500:500,
	SEC_MILI_1000:1000,
	SEC_MILI_2000:2000,
	SEC_MILI_3000:3000,
	SEC_MILI_4000:4000,
	SEC_MILI_5000:5000,
	
//	ACTION:'action',
	METHOD:'method',
	POST:'POST',
	GROUP_0:'0',
	GROUP_1:'1',
	GROUP_2:'2',
	GROUP_3:'3',
	GROUP_4:'4',
	GROUP_5:'5',
	GROUP_6:'6',
	GROUP_7:'7',
	GROUP_8:'8',
	GROUP_9:'9',
	SING_CODE:'signCode',
	MENU_TAIL:'-1',
	PRE:'이전',
	FIRST_VIEW:'첫화면',
	MINUS_1:'-1',
	NOT_EXIST:' 존재하지 않습니다.',
	SHARP:'#',
	SLASH:'/',
	ONE : 'one',
	END : 'end',
	START : 'start',
	MIDDLE : 'middle',
	SAVE:'저장',
	EDIT:'수정',
	HREF:'href',
	JS:'javascript:',
	UNDEFINED:'undefined',
	NO_CONDITION:'해당사항 없음',
	MODAL_MODIFY:'수정하시려면',
	MODAL_SAVE:'저장하시려면',
	MODAL_DEL:'삭제하시려면',
	ID_MODAL_CONFIRM :'id-modal-confirm',
	SEMI_COLON:';',
	RIGHT_BRACKET:'>',
	SCROLL_HEIGHT:'scrollHeight',
	PS:'ps',  
	POWERSHELL:'powershell',
	JESSION:'jessionid',
	LEFT:'left',
    BUTTON:'button',
    CONTENT_TYPE:'content-type',
    APP_JSON:'application/json',
    APP_JSON_EX:'application/json;charset=utf-8',
    JSON:'JSON',
    EXT_API:'.api',
    TR:'tr',
    TEXT_DANGER:'text-danger',
}
*/
