<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>

<script>
const Define = {
		SHOW: 'show',
		HIDE: 'hide',
		ACTION: 'action',
		ON_CLICK: 'onclick',
		DISABLED: 'disabled',
		SRC: 'src',
		DISPLAY: 'display',
		NONE: 'none',
		KEYUP: 'keyup',
		BLOCK: 'block',
		CLICK: 'click',
		SPAN: 'span',
		SEP: ',',
		SPACE: ' ',
		
		COUNT_0: 0,
		COUNT_1: 1,
		COUNT_2: 2,
		COUNT_3: 3,
		COUNT_4: 4,
		COUNT_5: 5,
		COUNT_6: 6,
		COUNT_7: 7,
		COUNT_8: 8,
		COUNT_9: 9,
		COUNT_10: 10,
		COUNT_15: 15,	
		
		QUESTION: '?',
		VISIBILITY: 'visibility',
		HIDDEN: 'hidden',
		
		INDEX_0: 0,
		INDEX_1: 1,
		INDEX_2: 2,
		INDEX_3: 3,
		INDEX_4: 4,	
		
		SIGNUP_SUCCESS: '회원 가입이 성공하였습니다.',
		STR_BLANK: '',
		INPUT: 'input',
		LABEL: 'label',
		YYYY_MM_DD: 'yyyy-mm-dd',
		SELECTED: 'selected',
		CHECKED: 'checked',
		COLON_CHECKED: ':checked',
		PAGE_0: 0,
		CLASS: 'class',
		ID: 'id',
		ASC: 'asc',
		DESC: 'desc',
//		CHECKED:':checked',
		DATA_SEQ: 'data-seq',
		DATA_ROAD:'data-road',
		DATA_DONG:'data-dong',
		DATA_REG_DTIME:'data-reg-dtime',
		DATA_DSR_SEQ:'data-dsr-seq',
		YES: 'yes',
		INSERT:'insert',
		EDIT:'edit',
		DELETE:'delete',
		UPDATE:'update',
		HOUR:'시',
		MONTH_1:1,
		DATA_LAT:'data-lat',
		DATA_LOG:'data-log',
		WIDTH:'width',
		HEIGHT:'height',
		STYLE:'style',
		START:'start',
		STOP:'stop',
		DATA_MODE:'data-mode',
		DATA_MODE_CAMERA:'data-mode-camera',
		CHATTING:'chatting',
		CMD:'cmd',
		NOT_CHATTING:'not-chatting',
		MENU:'menu',
		TEXT:'text',
		SEL:'sel',
		ENTER:'\n',
		
		MILI_SEC_1000:1000,
		MILI_SEC_2000:2000,
	    MILI_SEC_3000:3000,	    
	    MILI_SEC_4000:4000,
	    MILI_SEC_5000:5000,
	    MILI_SEC_6000:6000,
	    MILI_SEC_7000:7000,
	    MILI_SEC_8000:8000,
	    MILI_SEC_9000:9000,
	    MILI_SEC_500:500,
	    MILI_SEC_300:300,
	    MILI_SEC_200:200,
	    MILI_SEC_100:100,
	    		
		METHOD:'method',
		POST:'POST',
		
		GROUP_0:'0',
		GROUP_1:'1',
		GROUP_2:'2',
		GROUP_3:'3',
		GROUP_4:'4',
		GROUP_5:'5',
		GROUP_6:'6',
		GROUP_7:'7',
		GROUP_8:'8',
		GROUP_9:'9',
		
		SING_CODE:'signCode',
		MENU_TAIL:'-1',
		PRE:'이전',
		FIRST_VIEW:'첫화면',
		MINUS_1:'-1',
		NOT_EXIST:' 존재하지 않습니다.',
		SHARP:'#',
		SLASH:'/',
		ONE : 'one',
		END : 'end',
		//START : 'start',
		MIDDLE : 'middle',
		SAVE:'저장',
		EDIT:'수정',
		HREF:'href',
		JS:'javascript:',
		UNDEFINED:'undefined',
		NO_CONDITION:'해당사항 없음',
		MODAL_MODIFY:'수정하시려면',
		MODAL_SAVE:'저장하시려면',
		MODAL_DEL:'삭제하시려면',
		ID_MODAL_CONFIRM :'id-modal-confirm',
		SEMI_COLON:';',
		RIGHT_BRACKET:'>',
		SCROLL_HEIGHT:'scrollHeight',
		PS:'ps',  
		POWERSHELL:'powershell',
		JESSION:'jessionid',
		LEFT:'left',
	    BUTTON:'button',
	    CONTENT_TYPE:'content-type',
	    APP_JSON:'application/json',
	    APP_JSON_EX:'application/json;charset=utf-8',
	    JSON:'JSON',
	    EXT_API:'.api',
	    TR:'tr',
	    TEXT_DANGER:'text-danger',
	    KIOSK:'kiosk',
	    KIOSK_EX:'kiosk/',
	    WS:'ws',
	    WSS:'wss',
	    CUDA_WS:'/cuda-ws/',
	    NEXT:'next',  
	    COLON:':',
	    COLON_SLASH:'://',
	    UNDER:'_',
	    VIDEO:'video',
	    DASH_CAMERA:'-camera',
	    DATA_DASH:'data-',
		EXT_PNG:'.png',
		TYPE:'type',
		ERR_NOT_COND:'해당하는 타입이 없습니다.',
		HTTP:'http',
		HTTPS:'https',
		ON:'on',
		OFF:'off',
		//NEXT:'다음',
		//NEXT_STEP:'다음단계',
		NEXT_STEP:'다음 단계',		
		//RE:'다시',
		//RE_WATCH:'다시보기',
		RE_WATCH:'다시 보기',
		HTML_SPACE:'&nbsp;',
		ACTIVE:'active',
		NUM_MINUS_1:-1,
		NUM_0:0,
		NUM_1:1,
		NUM_2:2,
		NUM_3:3,
		NUM_4:4,
		NUM_5:5,
		NUM_6:6,
		NUM_7:7,
		NUM_8:8,
		NUM_9:9,
		NUM_10:10,		
		ENDED:'ended',		
		EXT_MP4:'.mp4',
 		QUALITY : 0.7,
		IMAGE : 'image/jpeg',
		IMAGE_PNG : 'image/png',
		FRONT : 'user',
		COMMA : ',',
		TRANSPARENT : 'background-color:transparent;',
		MILI_1000 : 1000,
		FRAME_6 : 6,		
// 		MENU : 'menu',
		URL : 'url',
		IMG: 'img',
		SPEECH:'speech',
		TO : 'to',
		LINE_20 : 20,
		LINE_30 : 30,
		ADMIN: 'admin',
		SECOND : 'second',
		FIRST : 'first',
		CLOSE : 'close',
		CMD_MENU : 'cmdMenu',
		INPUT_TYPE : 'inputType',
		SIGN : 'sign',
		BLANK : '_blank',
		TAG_A : 'a',
		FOCUS : 'focus',
		FOCUS_CLICK_KEYUP : 'focus click keyup',
		FOCUS_CLICK_KEYUP_MOUSEUP : 'focus click keyup mouseup',
		KEYUP_MOUSEUP:'mouseup keyup',
		CANVAS:'canvas',
		D2D:'2d',
		BASE64IMG:'base64Img',
		PX:'px',
	}
</script>